import type { Metadata } from "next";
import { Plus_Jakarta_Sans, IBM_Plex_Serif, Allura } from "next/font/google";
import "./globals.css";
import Header from './components/header'
import MobileNav from './components/mobile-nav'
import Footer from "./components/footer";
import { CartProvider } from './contexts/cart-context';

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-family-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const ibmPlexSerif = IBM_Plex_Serif({
  variable: "--font-family-serif",
  subsets: ["latin"],
  weight: ["600"],
});

const allura = Allura({
  variable: "--font-family-allura",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Ser Galgos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${plusJakartaSans.variable} ${ibmPlexSerif.variable} ${allura.variable} antialiased`}
      >
        <CartProvider>
          <Header />
            {children}
          <MobileNav />
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
